version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: pheonix_med
    environment:
      POSTGRES_USER: {PG_USER}
      POSTGRES_PASSWORD: {PG_PASSWORD}
      POSTGRES_DB: {PG_DB}
    ports:
      - {PG_PORT}: 5430
    volumes:
      - pheonixmed_db:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data: